"""empty message

Revision ID: a3f2ceb774bc
Revises: 6e63573b9349
Create Date: 2025-12-22 11:38:13.817438

"""

import sqlalchemy as sa
from alembic import op

from src.domains.detect.models import TaskStatus

# revision identifiers, used by Alembic.
revision = "a3f2ceb774bc"
down_revision = "6e63573b9349"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("detection_video", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum("PENDING", "STARTED", "FAILURE", "SUCCESS", name="taskstatus"),
                nullable=False,
                default="PENDING",
            )
        )
        batch_op.drop_column("task_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("detection_video", schema=None) as batch_op:
        batch_op.add_column(sa.Column("task_id", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("status")

    # ### end Alembic commands ###
