"""empty message

Revision ID: a43fe9efa189
Revises: 047ef4518315
Create Date: 2025-12-11 10:24:53.403650

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a43fe9efa189"
down_revision = "047ef4518315"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("detection_video", schema=None) as batch_op:
        batch_op.add_column(sa.Column("task_id", sa.String(), nullable=True))
        batch_op.alter_column("video_path", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("detection_video", schema=None) as batch_op:
        batch_op.alter_column("video_path", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("task_id")

    op.create_table(
        "_alembic_tmp_detection_video",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("model", sa.VARCHAR(), nullable=False),
        sa.Column("video_path", sa.VARCHAR(), nullable=True),
        sa.Column("user_video_id", sa.INTEGER(), nullable=False),
        sa.Column("task_id", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_video_id"],
            ["user_video.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
